spring:
  application:
    name: github-bot

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
  chat-id: ${TELEGRAM_CHAT_ID}

github:
  webhook:
    secret: ${GITHUB_WEBHOOK_SECRET}
